# Generated by Django 4.1.3 on 2023-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_table',
            name='message',
            field=models.TextField(),
        ),
    ]
