# Generated by Django 4.1.3 on 2023-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
